# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: A Career Change
email: jody.vanden@gmaile.com
description: >- # this means to ignore newlines until "baseurl:"
  I have a mechanical engineer degree and when I moved to Australia I found out
  that the industry in manufacturing here is not as big as I though. This is why
   I am doing a career change and try to go into Ruby dev. I chose Ruby as a
   language because it is friendly, massivly used in Australia and with a strong
    community.
  I know that inversting in junior might be annoying. But I am a fast learner
  and want to succed in this industry. And I know that technicaly I am not the
  best right now in the dev industry, but as a formal mechanical engineer I had
  to deal with a lot of technical problems.


baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  JodyVanden

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

  #Write an awesome description for your new site here. You can edit this
  # line in _config.yml. It will appear in your document head meta (for
  # Google search results) and in your feed.xml site description.
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
